name: Format
on: [pull_request]

jobs:
  check-format-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
        run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: ./typescript
      - name: Ensure formatting
        working-directory: ./typescript
        run: |
          pnpm install --frozen-lockfile
          pnpm format:check

  check-format-examples-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: ./examples/typescript
      - name: Ensure formatting
        working-directory: ./examples/typescript
        run: |
          pnpm install --frozen-lockfile
          pnpm format:check
